Repository phpmd/phpmd, pull requests merged in 2019-12, with the labels that each got.

#690 Add the new issue template config for GitHub
  .github/ISSUE_TEMPLATE/config.yml
Labels: Documentation

#696 Add "For Enterprise" page to PHPMD website
  src/site/resources/web/images/tidelift-demo-button.png
  src/site/resources/web/images/tidelift-learnmore-button.png
  src/site/rst/.index.xml
  src/site/rst/for-enterprise.rst
Labels: Website

#682 Add the latest phar file to the GitHub Pages to have a consistent URL
  bin/build-website.php
  src/site/rst/download/index.rst
Labels: Documentation, PHAR, Website

#708 Add PHPMD 2.8.0 changelog
  CHANGELOG
Labels: Documentation

#692 Add PHPMD 2.8.0 changelog
  CHANGELOG
Labels: Documentation

#709 Require PDepend 2.6
  CHANGELOG
  composer.json
Labels: Dependencies

#711 Fix website links and use common library for PHPMD and Pdepend
  .scrutinizer.yml
  .travis.yml
  bin/build-website.php
  composer.json
  src/site/config.php
  src/site/resources/layout.php
  src/site/rst/about.rst
  src/site/rst/documentation/index.rst
  src/site/rst/download/releases/index.rst
Labels: Documentation

#713 [Travis-CI] Fix unit tests failure detection
  .travis.yml
  src/test/php/PHPMD/Rule/CleanCode/UndefinedValiableTest.php
Labels: Bug, Testing
