Repository phpmd/phpmd, pull requests merged in 2019-10, with the labels that each got.

#679 Correct readme explaining ruleset and report.
  README.rst
Labels: Documentation

#684 Fix arrival version of UndefinedVariable
  src/main/resources/rulesets/cleancode.xml
Labels: Documentation

#644 Fixing a part of the PHPMD violations in PHPMD
  src/main/php/PHPMD/ParserFactory.php
  src/main/php/PHPMD/Rule/Naming/LongVariable.php
  src/main/php/PHPMD/Rule/Naming/ShortVariable.php
  src/main/php/PHPMD/RuleSetFactory.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/main/php/PHPMD/Writer/StreamWriter.php
Labels: Code Style, Refactoring

#686 Ignore all PHAR files, not just Composer's
  .gitignore
Labels: Dependencies

#685 Short variable apply improvements
  src/main/php/PHPMD/Rule/Naming/ShortVariable.php
Labels: Documentation, Refactoring

#695 Add keyword to let merged PRs auto-close issues
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Enhancement
