Repository phpmd/phpmd, pull requests merged in 2019-08, with the labels that each got.

#646 Add MissingImport link in the menu
  src/site/rst/documentation/index.rst
  src/site/rst/rules/index.rst
Labels: Documentation

#648 Move IfStatementAssignment to CleanCode
  src/site/rst/rules/index.rst
Labels: Documentation, Website

#651 Move the issue templates to the ISSUE_TEMPLATE directory
  .github/ISSUE_TEMPLATE/1_Bug.md
  .github/ISSUE_TEMPLATE/2_Feature_Proposal.md
  .github/ISSUE_TEMPLATE/3_Question.md
  .github/ISSUE_TEMPLATE/4_Documentation_and_Website_Issue.md
Labels: Bug, Documentation

#595 Add a renderer which writes an ANSI report string
  README.rst
  src/main/php/PHPMD/Renderer/AnsiRenderer.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/test/php/PHPMD/AbstractTest.php
  src/test/php/PHPMD/Renderer/AnsiRendererTest.php
  src/test/php/PHPMD/TextUI/CommandLineOptionsTest.php
Labels: Feature, Output

#652 Fix #650 Use pretty tables to handle multi-line
  src/site/rst/documentation/ant-task.rst
  src/site/rst/rules/cleancode.rst
  src/site/rst/rules/codesize.rst
  src/site/rst/rules/controversial.rst
  src/site/rst/rules/design.rst
  src/site/rst/rules/naming.rst
  src/site/rst/rules/unusedcode.rst
Labels: Documentation, Website

#656 Update deprecated PHPUnit calls
  src/test/php/PHPMD/AbstractTest.php
  src/test/php/PHPMD/Node/ASTNodeTest.php
  src/test/php/PHPMD/Node/ClassNodeTest.php
  src/test/php/PHPMD/Node/FunctionTest.php
  src/test/php/PHPMD/Node/MethodNodeTest.php
  src/test/php/PHPMD/ParserFactoryTest.php
  src/test/php/PHPMD/ParserTest.php
  src/test/php/PHPMD/Renderer/AnsiRendererTest.php
Labels: Testing

#657 Fix IfStatementAssignment violation message
  src/main/php/PHPMD/Rule/CleanCode/IfStatementAssignment.php
Labels: Bug

#659 Update RuleSetFactory.php
  src/main/php/PHPMD/RuleSetFactory.php
Labels: Compatibility, php7.4

#653 Optimize Composer autoloader when building Phar
  build.xml
Labels: Build scripts, Dependencies

#660 Add link to Tidelift
  .github/FUNDING.yml
  README.rst
Labels: Documentation

#641 Fix PHPDoc blocks
  src/main/php/PHPMD/AbstractNode.php
  src/main/php/PHPMD/PHPMD.php
  src/main/php/PHPMD/Renderer/JSONRenderer.php
  src/main/php/PHPMD/Rule/CleanCode/ElseExpression.php
  src/main/php/PHPMD/Rule/Design/TooManyMethods.php
  src/main/php/PHPMD/Rule/Design/TooManyPublicMethods.php
  src/main/php/PHPMD/Rule/UnusedPrivateField.php
  src/main/php/PHPMD/Rule/UnusedPrivateMethod.php
Labels: Bug, Documentation, Refactoring

#571 Add 'ignore-namespaces' option to DevelopmentCodeFragment
  src/main/php/PHPMD/Rule/Design/DevelopmentCodeFragment.php
  src/main/resources/rulesets/design.xml
  src/test/php/PHPMD/Rule/Design/DevelopmentCodeFragmentTest.php
  src/test/resources/files/Rule/Design/DevelopmentCodeFragment/testRuleAppliesToMethodWithinNamespace.php
  src/test/resources/files/Rule/Design/DevelopmentCodeFragment/testRuleNotAppliesToMethodWithinNamespaceByDefault.php
Labels: Enhancement

#662 Add 'ignore-namespaces' option documentation
  src/site/rst/rules/design.rst
Labels: Documentation

#665 Fix documentation table misalignment
  src/site/rst/rules/design.rst
Labels: Documentation

#666 Fix readme link RST format
  README.rst
Labels: Documentation

#667 Remove the --prefer-lowest and add a platform config for the phar file
  build.xml
Labels: Bug, Build scripts, PHAR

#497 Implement Undefined Variable Rule
  src/bin/phpmd
  src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php
  src/main/resources/rulesets/cleancode.xml
  src/test/php/PHPMD/Rule/CleanCode/UndefinedValiableTest.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleAppliesToUndefinedVariable.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleAppliesToUndefinedVariableOnArray.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleAppliesToUndefinedVariableOnArrayWithKeys.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleAppliesToUndefinedVariableWithDefinedVariable.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleDoesNotApplyToSuperGlobals.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleDoesNotApplyToUsedProperties.php
Labels: Feature

#669 Replace xdebug with phpdbg for code coverage
  .travis.yml
Labels: Dependencies, Testing
