Repository phpmd/phpmd, pull requests merged in 2019-06, with the labels that each got.

#552 Use PHP 7.1 in AppVeyor builds
  appveyor.yml
Labels: Bug, Testing

#605 Fix #603 Build the website as static files using pure PHP
  .gitattributes
  .gitignore
  .travis.yml
  bin/build-website.php
  composer.json
  composer.lock
  src/site/resources/layout.php
  src/site/rst/download/.index.xml
Labels: Website

#608 Handle anchor links and use direct links whenever possible
  bin/build-website.php
  src/site/rst/rules/index.rst
Labels: Bug, Documentation, Website

#572 Allowing @suppressWarnings
  src/main/php/PHPMD/Node/Annotation.php
  src/test/php/PHPMD/Node/AnnotationTest.php
  src/test/php/PHPMD/Node/MethodNodeTest.php
  src/test/resources/files/Node/MethodNode/testHasSuppressWarningsIgnoresCaseFirstLetter.php
Labels: Enhancement

#567 minor fix index.rst
  src/site/rst/rules/index.rst
Labels: Bug, Documentation, Website

#606 Use BSD 3-clause license template
  LICENSE
Labels: Documentation, Enhancement

#566 Add usage example
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
Labels: CLI, Documentation

#604 Rename mikey179/vfsStream to mikey179/vfsstream to prevent composer error
  composer.json
  composer.lock
Labels: Bug, Dependencies

#598 Fix a bug in the renderer autodiscovery
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
Labels: Bug, CLI

#575 UnusedFormalParameter false positive in string compound variable
  src/main/php/PHPMD/Rule/UnusedFormalParameter.php
  src/test/php/PHPMD/Rule/UnusedFormalParameterTest.php
  src/test/resources/files/Rule/UnusedFormalParameter/testRuleDoesNotApplyToFormalParameterUsedAsParameterInStringCompoundVariable.php
  src/test/resources/files/Rule/UnusedFormalParameter/testRuleDoesNotApplyToFormalParameterUsedInStringCompoundVariable.php
Labels: Bug

#565 Add example for modifying properties in a rule set
  src/site/rst/documentation/creating-a-ruleset.rst
Labels: Documentation

#599 Fix package type
  composer.json
Labels: Bug, Documentation

#579 Add support for setting a maximum priority
  src/main/php/PHPMD/Rule.php
  src/main/php/PHPMD/RuleSetFactory.php
  src/main/php/PHPMD/TextUI/Command.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/site/rst/documentation/ant-task.rst
  src/site/rst/documentation/index.rst
  src/test/php/PHPMD/RuleSetFactoryTest.php
  src/test/php/PHPMD/TextUI/CommandLineOptionsTest.php
  src/test/resources/files/rulesets/refset3.xml
Labels: CLI, Feature

#382 Ignore isser-, hasser-, wither-method for TooManyMethods
  src/main/resources/rulesets/codesize.xml
  src/test/php/PHPMD/Rule/Design/TooManyMethodsTest.php
  src/test/php/PHPMD/Rule/Design/TooManyPublicMethodsTest.php
Labels: Enhancement, On Hold

#612 Remove IRC, add Gitter & reword
  src/site/rst/support/index.rst
Labels: Documentation, Website

#611 Remove section about commercial support
  src/site/rst/support/index.rst
Labels: Website

#614 Remove API docs that do not exist anymore
  README.rst
Labels: Documentation

#615 Added Gitter badge
  README.rst
Labels: Documentation
