Repository phpmd/phpmd, pull requests merged in 2019-07, with the labels that each got.

#617 Replace Travis build notification from IRC to the new Gitter core channel
  .travis.yml
Labels: Build scripts, Testing

#609 Fix main logo link
  src/site/resources/layout.php
Labels: Bug, Documentation, Website

#620 Add PHPMD Gitter Community Channel notifications
  .travis.yml
Labels: Build scripts, Enhancement

#618 Add badges for the monthly and total downloads
  README.rst
Labels: Documentation, Enhancement

#622 Pick 2.6.1 release notes
  CHANGELOG
  build.properties
  src/site/docx/changes.xml
Labels: Documentation

#621 Update about PHPMD wording
  src/site/rst/about.rst
Labels: Documentation, Website

#623 Extend test matrix & do only one job per build on Travis
  .travis.yml
  build.xml
  composer.json
  composer.lock
Labels: Build scripts, Testing, php7.2, php7.3

#405 Add JSON Renderer for Report
  README.rst
  src/bin/phpmd
  src/main/php/PHPMD/Renderer/JSONRenderer.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/site/rst/documentation/index.rst
  src/test/php/PHPMD/AbstractTest.php
  src/test/php/PHPMD/Renderer/JSONRendererTest.php
  src/test/php/PHPMD/TextUI/CommandLineOptionsTest.php
  src/test/php/PHPMD/TextUI/CommandTest.php
  src/test/resources/files/renderer/json_renderer_expected.json
  src/test/resources/files/renderer/json_renderer_processing_errors.json
Labels: CLI, Feature, Output

#625 Skip DuplicatedArrayKey rule check, if there is no array key...
  src/main/php/PHPMD/Rule/CleanCode/DuplicatedArrayKey.php
  src/test/resources/files/Rule/CleanCode/DuplicatedArrayKey/testRuleNotAppliesToFunctionWithNonAssotiativeArrayDefinition.php
Labels: Bug

#626 Convert special chars in violation description for XML output
  src/main/php/PHPMD/Renderer/XMLRenderer.php
  src/test/php/PHPMD/AbstractTest.php
  src/test/php/PHPMD/Renderer/XMLRendererTest.php
  src/test/resources/files/renderer/xml_renderer_expected1.xml
Labels: Bug, Output

#627 Remove composer.lock
  .gitignore
  .travis.yml
  composer.lock
Labels: Dependencies, RFC

#631 Fix url to "How to create a custom rule set" documentation page
  src/site/rst/documentation/index.rst
Labels: Website

#633 Fix AppVeyor build
  appveyor.yml
Labels: Build scripts, Testing

#632 Use local PHPUnit in Scrutinizer
  .scrutinizer.yml
Labels: Build scripts, Compatibility, Testing

#636 #321 Inspection: missing class import
  src/main/php/PHPMD/Rule/CleanCode/MissingImport.php
  src/main/resources/rulesets/cleancode.xml
  src/site/rst/rules/cleancode.rst
  src/test/php/PHPMD/Rule/CleanCode/MissingImportTest.php
  src/test/resources/files/Rule/CleanCode/MissingImport/testRuleAppliesToClassWithNotImportedDependencies.php
  src/test/resources/files/Rule/CleanCode/MissingImport/testRuleAppliesToFunctionWithNotImportedDependencies.php
  src/test/resources/files/Rule/CleanCode/MissingImport/testRuleNotAppliesToClassWithOnlyImportedDependencies.php
  src/test/resources/files/Rule/CleanCode/MissingImport/testRuleNotAppliesToClassWithSelfAndStaticCalls.php
  src/test/resources/files/Rule/CleanCode/MissingImport/testRuleNotAppliesToClassWithoutAnyDependencies.php
  src/test/resources/files/Rule/CleanCode/MissingImport/testRuleNotAppliesToFunctionWithOnlyImportedDependencies.php
  src/test/resources/files/Rule/CleanCode/MissingImport/testRuleNotAppliesToFunctionWithoutAnyDependencies.php
Labels: Feature

#643 Revert #528 as CI tool is not a sufficient reason to drop a PHP version
  .travis.yml
  composer.json
  src/main/php/PHPMD/Renderer/JSONRenderer.php
  src/main/php/PHPMD/Rule/CleanCode/MissingImport.php
  src/site/rst/download/index.rst
Labels: Compatibility

#642 Release 2.7.0
  CHANGELOG
  build.properties
  src/site/docx/changes.xml
Labels: Documentation, Website

#635 Issue templates
  .gitattributes
  .github/1_Bug.md
  .github/2_Feature_Proposal.md
  .github/3_Question.md
  .github/4_Documentation_and_Website_Issue.md
Labels: Documentation, Enhancement

#555 Use XdebugHandler to avoid performance issues
  composer.json
  src/bin/phpmd
Labels: Compatibility, Dependencies

#645 Fix the doc of Clean Code Rules.
  src/site/rst/rules/cleancode.rst
Labels: Documentation
