Repository phpmd/phpmd, pull requests merged in 2020-02, with the labels that each got.

#733 Fix #732: Add __serialize and __unserialize to list of ignored methods for camelCase rule
  CHANGELOG
  composer.json
  src/main/php/PHPMD/Rule/Controversial/CamelCaseMethodName.php
  src/test/php/PHPMD/Rule/Controversial/CamelCaseMethodNameTest.php
  src/test/resources/files/Rule/Controversial/CamelCaseMethodName/testRuleDoesNotApplyForMagicMethods.php
Labels: Compatibility, Enhancement, php7.4

#736 Add the release date for 2.8.2
  CHANGELOG
Labels: Documentation

#737 Allowing custom exclusion for StaticAccess by extending the class
  src/main/php/PHPMD/Rule/CleanCode/StaticAccess.php
Labels: Enhancement

#719 Fix #717 restore RST files in website
  .travis.yml
  src/site/resources/layout.php
Labels: Documentation, Website
