Repository phpmd/phpmd, pull requests merged in 2020-05, with the labels that each got.

#768 Remove Class Aliases
  src/bin/phpmd
Labels: Refactoring, php5.x

#756 Ease testing of simple rule standard cases
  src/main/php/PHPMD/AbstractNode.php
  src/main/php/PHPMD/Rule/UnusedPrivateMethod.php
  src/main/php/PHPMD/TextUI/Command.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/test/php/PHPMD/AbstractStaticTest.php
  src/test/php/PHPMD/AbstractTest.php
  src/test/php/PHPMD/Rule/CleanCode/UndefinedVariableTest.php
  src/test/php/PHPMD/Rule/Design/TooManyMethodsTest.php
  src/test/php/PHPMD/RuleSetTest.php
Labels: Enhancement, Refactoring, Testing

#770 Fix #769 Handle deconstruction assignation for undefined variable
  src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleDoesNotApplyToSymmetricArrayDestructuring.php
Labels: Bug, php7.1

#779 Adds missing ansi renderer to website documentation
  src/site/rst/documentation/index.rst
Labels: Documentation

#777 Remove now superfluous var annotations
  src/main/php/PHPMD/RuleSetFactory.php
Labels: Refactoring

#781 Fix #714 static:: and self:: properties access
  src/main/php/PHPMD/Rule/AbstractLocalVariable.php
  src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleAppliesToStaticProperties.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleDoesNotApplyToStaticProperties.php
Labels: Bug

#785 Optimize UnusedFormalParameter
  src/main/php/PHPMD/Rule/UnusedFormalParameter.php
Labels: Refactoring

#784 Fix #672 Handle passing-by-reference in native PHP functions
  src/main/php/PHPMD/Rule/AbstractLocalVariable.php
  src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleDoesNotApplyToPassingByReferences.php
Labels: Bug

#787 Add missing methods to AbstractTest to handle more various apply/notApply series
  src/test/php/PHPMD/AbstractTest.php
Labels: Refactoring, Testing

#789 Update CONTRIBUTING to point out to the correct coding standard
  CONTRIBUTING.md
Labels: Code Style, Documentation
