Repository phpmd/phpmd, pull requests merged in 2020-04, with the labels that each got.

#748 Add guiding check lists...
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation, Enhancement, RFC

#749 Add allow-underscore option
  src/main/php/PHPMD/Rule/Controversial/CamelCaseParameterName.php
  src/main/php/PHPMD/Rule/Controversial/CamelCaseVariableName.php
  src/main/resources/rulesets/controversial.xml
  src/site/rst/rules/controversial.rst
  src/test/php/PHPMD/Rule/Controversial/CamelCaseParameterNameTest.php
  src/test/php/PHPMD/Rule/Controversial/CamelCaseVariableNameTest.php
  src/test/resources/files/Rule/Controversial/CamelCaseParameterName/testRuleDoesApplyForInparameterNameWithUnderscore.php
  src/test/resources/files/Rule/Controversial/CamelCaseParameterName/testRuleDoesApplyForParameterNameWithCapital.php
  src/test/resources/files/Rule/Controversial/CamelCaseParameterName/testRuleDoesNotApplyForValidParameterName.php
  src/test/resources/files/Rule/Controversial/CamelCaseParameterName/testRuleDoesNotApplyForValidParameterNameWithUnderscoreWhenAllowed.php
  src/test/resources/files/Rule/Controversial/CamelCaseVariableName/testRuleDoesNotApplyForValidVariableNameWithUnderscoreWhenAllowed.php
Labels: Configuration, Feature

#752 Remove code redundancy around config file path
  src/main/php/PHPMD/ParserFactory.php
Labels: CLI, Configuration, Refactoring

#754 Fix #720 undefined variable in foreach when passed by reference
  src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php
  src/test/php/PHPMD/Rule/CleanCode/UndefinedValiableTest.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleDoesNotApplyToKeyReferencePair.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleDoesNotApplyToKeyValuePair.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleDoesNotApplyToReferences.php
Labels: Bug, PDepend

#757 Report mock convenience methods
  src/test/php/PHPMD/AbstractTest.php
  src/test/php/PHPMD/ParserFactoryTest.php
  src/test/php/PHPMD/ParserTest.php
  src/test/php/PHPMD/Regression/ExcessivePublicCountRuleNeverExecutedTicket015Test.php
  src/test/php/PHPMD/Regression/InvalidUnusedLocalVariableAndFormalParameterTicket007Test.php
  src/test/php/PHPMD/Regression/StaticVariablesFlaggedAsUnusedTicket020Test.php
  src/test/php/PHPMD/Regression/SuperGlobalsFlaggedAsUnusedTicket019Test.php
  src/test/php/PHPMD/Regression/SuppressWarningsNotAppliesToUnusedPrivateMethod036Test.php
  src/test/php/PHPMD/Regression/UnusedParameterArgvTicket14990109Test.php
  src/test/php/PHPMD/Renderer/AnsiRendererTest.php
  src/test/php/PHPMD/Renderer/HTMLRendererTest.php
  src/test/php/PHPMD/Renderer/JSONRendererTest.php
  src/test/php/PHPMD/Renderer/TextRendererTest.php
  src/test/php/PHPMD/Renderer/XMLRendererTest.php
  src/test/php/PHPMD/Rule/CleanCode/DuplicatedArrayKeyTest.php
  src/test/php/PHPMD/Rule/CleanCode/ElseExpressionTest.php
  src/test/php/PHPMD/Rule/CleanCode/IfStatementAssignmentTest.php
  src/test/php/PHPMD/Rule/CleanCode/MissingImportTest.php
  src/test/php/PHPMD/Rule/CleanCode/StaticAccessTest.php
  src/test/php/PHPMD/Rule/CleanCode/UndefinedValiableTest.php
  src/test/php/PHPMD/Rule/Controversial/CamelCaseMethodNameTest.php
  src/test/php/PHPMD/Rule/Controversial/CamelCaseParameterNameTest.php
  src/test/php/PHPMD/Rule/Controversial/CamelCasePropertyNameTest.php
  src/test/php/PHPMD/Rule/Controversial/CamelCaseVariableNameTest.php
  src/test/php/PHPMD/Rule/CyclomaticComplexityTest.php
  src/test/php/PHPMD/Rule/Design/CountInLoopExpressionTest.php
  src/test/php/PHPMD/Rule/Design/CouplingBetweenObjectsTest.php
  src/test/php/PHPMD/Rule/Design/DepthOfInheritanceTest.php
  src/test/php/PHPMD/Rule/Design/DevelopmentCodeFragmentTest.php
  src/test/php/PHPMD/Rule/Design/EmptyCatchBlockTest.php
  src/test/php/PHPMD/Rule/Design/EvalExpressionTest.php
  src/test/php/PHPMD/Rule/Design/ExitExpressionTest.php
  src/test/php/PHPMD/Rule/Design/GotoStatementTest.php
  src/test/php/PHPMD/Rule/Design/LongClassTest.php
  src/test/php/PHPMD/Rule/Design/LongMethodTest.php
  src/test/php/PHPMD/Rule/Design/LongParameterListTest.php
  src/test/php/PHPMD/Rule/Design/NpathComplexityTest.php
  src/test/php/PHPMD/Rule/Design/NumberOfChildrenTest.php
  src/test/php/PHPMD/Rule/Design/TooManyFieldsTest.php
  src/test/php/PHPMD/Rule/Design/TooManyMethodsTest.php
  src/test/php/PHPMD/Rule/Design/TooManyPublicMethodsTest.php
  src/test/php/PHPMD/Rule/Design/WeightedMethodCountTest.php
  src/test/php/PHPMD/Rule/ExcessivePublicCountTest.php
  src/test/php/PHPMD/Rule/Naming/BooleanGetMethodNameTest.php
  src/test/php/PHPMD/Rule/Naming/ConstantNamingConventionsTest.php
  src/test/php/PHPMD/Rule/Naming/ConstructorWithNameAsEnclosingClassTest.php
  src/test/php/PHPMD/Rule/Naming/LongVariableTest.php
  src/test/php/PHPMD/Rule/Naming/ShortMethodNameTest.php
  src/test/php/PHPMD/Rule/Naming/ShortVariableTest.php
  src/test/php/PHPMD/Rule/UnusedFormalParameterTest.php
  src/test/php/PHPMD/Rule/UnusedLocalVariableTest.php
  src/test/php/PHPMD/Rule/UnusedPrivateFieldTest.php
  src/test/php/PHPMD/Rule/UnusedPrivateMethodTest.php
  src/test/php/PHPMD/RuleSetTest.php
Labels: Refactoring, Testing

#750 Get string/boolean/integer property fallback
  src/main/php/PHPMD/AbstractRule.php
  src/test/php/PHPMD/RuleTest.php
Labels: Enhancement

#758 AbstractTest Cleanup
  composer.json
  src/test/php/PHPMD/AbstractTest.php
Labels: Dependencies, Refactoring, Testing

#761 Ignoring any XML files in the root
  .gitignore
Labels: Build scripts, Code Style, Dependencies, Enhancement

#496 Add rule for PHP's @ operator
  src/main/php/PHPMD/Rule/CleanCode/ErrorControlOperator.php
  src/main/resources/rulesets/cleancode.xml
  src/site/rst/rules/cleancode.rst
  src/site/rst/rules/index.rst
  src/test/php/PHPMD/Rule/CleanCode/ErrorControlOperatorTest.php
  src/test/php/PHPMD/Rule/Design/DevelopmentCodeFragmentTest.php
  src/test/resources/files/Rule/CleanCode/ErrorControlOperator/testAppliedToClassesAndMethods.php
  src/test/resources/files/Rule/CleanCode/ErrorControlOperator/testAppliesToErrorControlOperatorInFunction.php
  src/test/resources/files/Rule/CleanCode/ErrorControlOperator/testDoesNotApplyToOtherUnaryOperatorsInFunction.php
Labels: Feature

#747 Long variable subtract suffix
  src/main/php/PHPMD/Rule/Naming/LongVariable.php
  src/main/resources/rulesets/naming.xml
  src/site/rst/rules/naming.rst
  src/test/php/PHPMD/Rule/Naming/LongVariableTest.php
  src/test/resources/files/Rule/Naming/LongVariable/testRuleAppliesToVariableNameLongerThanThresholdWithMultipleSuffixesDefined.php
  src/test/resources/files/Rule/Naming/LongVariable/testRuleAppliesToVariableNameLongerThanThresholdWithSuffixSubtracted.php
  src/test/resources/files/Rule/Naming/LongVariable/testRuleAppliesToVariableNameSuffixIsNotSubtractedWhenNotASuffix.php
  src/test/resources/files/Rule/Naming/LongVariable/testRuleAppliesToVariableNameWithEmptySubtractSuffixes.php
  src/test/resources/files/Rule/Naming/LongVariable/testRuleNotAppliesToVariableNameSmallerThanThresholdWithSuffixSubtracted.php
Labels: Feature

#529 Replaced HTML renderer with new "pretty HTML" renderer
  src/main/php/PHPMD/Renderer/HTMLRenderer.php
  src/test/php/PHPMD/Renderer/HTMLRendererTest.php
Labels: Feature, Output
