Repository phpmd/phpmd, pull requests merged in 2020-09, with the labels that each got.

#795 Prepare a changelog for version 2.9.0
  CHANGELOG
Labels: Documentation

#818 Fixed undefined index referring
  src/main/php/PHPMD/Rule/AbstractLocalVariable.php
Labels: Needs Tests

#821 Upgrade build version number for next patch
  build.properties
Labels: Bug

#823 Fix #714 Improve static member detection
  src/main/php/PHPMD/Rule/AbstractLocalVariable.php
  src/test/php/PHPMD/AbstractTest.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleDoesNotApplyToCallsWithStaticProperties.php
Labels: Bug

#825 Add Changelog for 2.9.1
  CHANGELOG
Labels: Documentation
