Repository phpmd/phpmd, pull requests merged in 2021-02, with the labels that each got.

#788 #739 Add unit test to demonstrate the class begin line issue
  composer.json
  src/main/php/PHPMD/Rule/Design/TooManyPublicMethods.php
  src/test/php/PHPMD/Rule/Design/TooManyPublicMethodsTest.php
  src/test/resources/files/Rule/Design/TooManyPublicMethods/testRuleApplyToBasicClass.php
Labels: Bug

#849 Remove the incorrect robots.txt and the reference in the site.ini
  src/site/resources/config/site.ini
  src/site/rst/robots.txt
Labels: Website

#827 Fix #826 consider foreach exception only for direct children
  src/main/php/PHPMD/Rule/Naming/ShortVariable.php
  src/test/php/PHPMD/Rule/Naming/ShortVariableTest.php
  src/test/resources/files/Rule/Naming/ShortVariable/testRuleNotAppliesToTryCatchBlocksInsideForeach.php
Labels: Bug

#772 Rename setIgnorePattern to addIgnorePatterns and getIgnorePattern to …
  src/main/php/PHPMD/PHPMD.php
  src/main/php/PHPMD/ParserFactory.php
  src/main/php/PHPMD/TextUI/Command.php
  src/test/php/PHPMD/ParserFactoryTest.php
Labels: Deprecations, Refactoring

#838 Change the naming error where possible
  src/main/php/PHPMD/ParserFactory.php
  src/main/php/PHPMD/Renderer/HTMLRenderer.php
Labels: Refactoring

#872 Change exit code on processing errors
  README.rst
  src/main/php/PHPMD/PHPMD.php
  src/main/php/PHPMD/TextUI/Command.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/site/rst/documentation/index.rst
  src/test/php/PHPMD/PHPMDTest.php
  src/test/php/PHPMD/TextUI/CommandLineOptionsTest.php
  src/test/php/PHPMD/TextUI/CommandTest.php
  src/test/resources/files/pmd/single-directory.xml
  src/test/resources/files/source/source_with_parse_error.php
Labels: Feature
