Repository phpmd/phpmd, pull requests merged in 2021-04, with the labels that each got.

#874 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Documentation

#876 Added option --update-baseline to update an existing phpmd.baseline.xml
  README.rst
  src/main/php/PHPMD/Baseline/BaselineMode.php
  src/main/php/PHPMD/Baseline/BaselineValidator.php
  src/main/php/PHPMD/PHPMD.php
  src/main/php/PHPMD/Report.php
  src/main/php/PHPMD/TextUI/Command.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/site/rst/documentation/index.rst
  src/test/php/PHPMD/AbstractStaticTest.php
  src/test/php/PHPMD/Baseline/BaselineValidatorTest.php
  src/test/php/PHPMD/PHPMDTest.php
  src/test/php/PHPMD/Regression/AcceptsFilesAndDirectoriesAsInputTicket001Test.php
  src/test/php/PHPMD/Regression/ExcessivePublicCountWorksCorrectlyWithStaticMethodsTest.php
  src/test/php/PHPMD/Regression/MaximumNestingLevelTicket24975295Test.php
  src/test/php/PHPMD/ReportTest.php
  src/test/php/PHPMD/TextUI/CommandLineOptionsTest.php
  src/test/php/PHPMD/TextUI/CommandTest.php
  src/test/resources/files/TextUI/Command/UpdateBaseline/ClassWithMultipleViolations.php
  src/test/resources/files/TextUI/Command/UpdateBaseline/expected.baseline.xml
  src/test/resources/files/TextUI/Command/UpdateBaseline/phpmd.baseline.xml
Labels: Feature

#786 Add convenience method AbstractNode::findChildrenOfTypeVariable()
  src/main/php/PHPMD/AbstractNode.php
  src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php
  src/main/php/PHPMD/Rule/Controversial/CamelCaseVariableName.php
  src/main/php/PHPMD/Rule/Controversial/Superglobals.php
  src/main/php/PHPMD/Rule/Naming/LongVariable.php
  src/main/php/PHPMD/Rule/Naming/ShortVariable.php
  src/main/php/PHPMD/Rule/UnusedFormalParameter.php
  src/main/php/PHPMD/Rule/UnusedLocalVariable.php
Labels: Needs Tests, Refactoring

#856 adds checkstyle compatible renderer, suitable for cs2pr or reviewdog
  README.rst
  src/main/php/PHPMD/Renderer/CheckStyleRenderer.php
  src/main/php/PHPMD/Renderer/XMLRenderer.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/test/php/PHPMD/Renderer/CheckStyleRendererTest.php
  src/test/php/PHPMD/TextUI/CommandLineOptionsTest.php
  src/test/php/PHPMD/TextUI/CommandTest.php
Labels: Feature

#839 Cleancode rules
  src/main/php/PHPMD/AbstractNode.php
  src/main/php/PHPMD/Renderer/HTMLRenderer.php
  src/main/php/PHPMD/Report.php
  src/main/php/PHPMD/RuleSet.php
  src/main/php/PHPMD/RuleSetFactory.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/main/php/PHPMD/Writer/StreamWriter.php
Labels: Refactoring

#879 Document junit export using third-party
  src/site/resources/web/junit.xslt
  src/site/rst/documentation/index.rst
Labels: Documentation

#828 Fix #672 Try global function if namespaced one is not found
  src/main/php/PHPMD/Rule/AbstractLocalVariable.php
Labels: Bug
