Repository phpmd/phpmd, pull requests merged in 2021-07, with the labels that each got.

#904 Prepare the release for version 2.10.2
  CHANGELOG
  build.properties
  composer.json
Labels: Documentation

#905 Fix #884 Avoid unused parameters on PHP 8: Constructor property
  src/main/php/PHPMD/Rule/UnusedFormalParameter.php
  src/test/php/PHPMD/Rule/UnusedFormalParameterTest.php
  src/test/resources/files/Rule/UnusedFormalParameter/testRuleDoesNotApplyToPropertyPromotionParameters.php
Labels: Bug, php8.0, php8.x

#906 Fix false positive with static variable in function. fixes #870
  src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php
  src/test/resources/files/Rule/CleanCode/UndefinedVariable/testRuleDoesNotApplyToStaticVariableInFunction.php
Labels: Bug
