Repository phpmd/phpmd, pull requests merged in 2023-10, with the labels that each got.

#1041 Mention public key used for signing the Phars
  src/site/rst/download/index.rst
Labels: Documentation, Website, Build scripts, PHAR

#1036 Allow option and value separated with equal sign
  README.rst
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/main/php/PHPMD/Utility/ArgumentsValidator.php
  src/test/php/PHPMD/TextUI/CommandLineOptionsTest.php
Labels: Enhancement

#1042 Document installation with PHIVE
  src/site/rst/download/index.rst
Labels: Documentation, Website, PHAR
