Repository phpmd/phpmd, pull requests merged in 2024-05, with the labels that each got.

#776 RuleSet::getRuleByName throw exception
  src/main/php/PHPMD/RuleByNameNotFoundException.php
  src/main/php/PHPMD/RuleSet.php
  src/test/php/PHPMD/RuleSetTest.php
Labels: Refactoring

#982 Create common utility to handle exceptions lists
  src/main/php/PHPMD/AbstractRule.php
  src/main/php/PHPMD/Rule.php
  src/main/php/PHPMD/Rule/CleanCode/BooleanArgumentFlag.php
  src/main/php/PHPMD/Rule/CleanCode/StaticAccess.php
  src/main/php/PHPMD/Rule/Design/TooManyMethods.php
  src/main/php/PHPMD/Rule/Naming/LongClassName.php
  src/main/php/PHPMD/Rule/Naming/LongVariable.php
  src/main/php/PHPMD/Rule/Naming/ShortClassName.php
  src/main/php/PHPMD/Rule/Naming/ShortMethodName.php
  src/main/php/PHPMD/Rule/Naming/ShortVariable.php
  src/main/php/PHPMD/Rule/UnusedLocalVariable.php
  src/main/php/PHPMD/Utility/ExceptionsList.php
  src/main/php/PHPMD/Utility/Strings.php
Labels: Refactoring, RFC

#1133 [3.x] Replace usages of get_class() by ::class
  src/main/php/PHPMD/AbstractNode.php
  src/main/php/PHPMD/Baseline/BaselineValidator.php
  src/main/php/PHPMD/Cache/Model/ResultCacheState.php
  src/main/php/PHPMD/Renderer/BaselineRenderer.php
  src/test/php/PHPMD/ReportTest.php
Labels: Enhancement, Code Style, Refactoring

#1113 Add php-cs-fixer as a developer tool
  .github/workflows/codestyle.yml
  .gitignore
  .php-cs-fixer.php
  composer.json
  src/main/php/PHPMD/Renderer/CheckStyleRenderer.php
  src/main/php/PHPMD/Rule/CleanCode/IfStatementAssignment.php
Labels: Code Style

#1135 Fix missing @throws
  src/main/php/PHPMD/PHPMD.php
  src/main/php/PHPMD/Parser.php
  src/main/php/PHPMD/ParserFactory.php
  src/main/php/PHPMD/TextUI/Command.php
Labels: Configuration, Code Style, PHPStan

#1140 [3.x] Assert something to prevent risky tests
  src/test/php/PHPMD/Regression/AcceptsFilesAndDirectoriesAsInputTicket001RegressionTest.php
  src/test/php/PHPMD/Regression/MaximumNestingLevelTicket24975295RegressionTest.php
Labels: Bug, Testing

#1142 [3.x] Use Value as Data Provider Key
  src/test/php/PHPMD/AbstractStaticTestCase.php
Labels: Enhancement, Testing

#1154 Convert consts to enums
  src/bin/phpmd
  src/conf/phar_bootstrap.stub
  src/main/php/PHPMD/Baseline/BaselineMode.php
  src/main/php/PHPMD/Baseline/BaselineValidator.php
  src/main/php/PHPMD/Cache/Model/ResultCacheStrategy.php
  src/main/php/PHPMD/Cache/ResultCacheFileFilter.php
  src/main/php/PHPMD/TextUI/Command.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/main/php/PHPMD/TextUI/ExitCode.php
  src/test/php/PHPMD/Baseline/BaselineValidatorTest.php
  src/test/php/PHPMD/Cache/ResultCacheEngineFactoryTest.php
  src/test/php/PHPMD/Cache/ResultCacheFileFilterTest.php
  src/test/php/PHPMD/PHPMDTest.php
  src/test/php/PHPMD/ReportTest.php
  src/test/php/PHPMD/TextUI/CommandLineOptionsTest.php
  src/test/php/PHPMD/TextUI/CommandTest.php
Labels: Refactoring

#1156 Update PHPStan to version 1.11
  composer.json
Labels: Dependencies, PHPStan

#1155 Disable no_unset_on_property
  .php-cs-fixer.php
Labels: Configuration, Code Style

#1150 Mark class internals as private
  src/main/php/PHPMD/AbstractRule.php
  src/main/php/PHPMD/Rule/CleanCode/BooleanArgumentFlag.php
  src/main/php/PHPMD/Utility/ExceptionsList.php
Labels: Refactoring

#1149 Move functions to where they are used and mark them private
  src/main/php/PHPMD/Rule/AbstractLocalVariable.php
  src/main/php/PHPMD/Rule/UnusedFormalParameter.php
  src/main/php/PHPMD/Rule/UnusedLocalVariable.php
Labels: Refactoring

#1153 Use constructor property promotion
  src/main/php/PHPMD/AbstractNode.php
  src/main/php/PHPMD/Baseline/BaselineFileFinder.php
  src/main/php/PHPMD/Baseline/BaselineValidator.php
  src/main/php/PHPMD/Baseline/ViolationBaseline.php
  src/main/php/PHPMD/Cache/Model/ResultCacheKey.php
  src/main/php/PHPMD/Cache/Model/ResultCacheState.php
  src/main/php/PHPMD/Cache/ResultCacheEngine.php
  src/main/php/PHPMD/Cache/ResultCacheEngineFactory.php
  src/main/php/PHPMD/Cache/ResultCacheFileFilter.php
  src/main/php/PHPMD/Cache/ResultCacheKeyFactory.php
  src/main/php/PHPMD/Cache/ResultCacheUpdater.php
  src/main/php/PHPMD/Cache/ResultCacheWriter.php
  src/main/php/PHPMD/Console/Output.php
  src/main/php/PHPMD/Console/StreamOutput.php
  src/main/php/PHPMD/Node/ASTNode.php
  src/main/php/PHPMD/Node/AbstractCallableNode.php
  src/main/php/PHPMD/Node/AbstractTypeNode.php
  src/main/php/PHPMD/Node/Annotation.php
  src/main/php/PHPMD/Node/ClassNode.php
  src/main/php/PHPMD/Node/EnumNode.php
  src/main/php/PHPMD/Node/FunctionNode.php
  src/main/php/PHPMD/Node/InterfaceNode.php
  src/main/php/PHPMD/Node/MethodNode.php
  src/main/php/PHPMD/Node/NodeInfo.php
  src/main/php/PHPMD/Node/TraitNode.php
  src/main/php/PHPMD/Parser.php
  src/main/php/PHPMD/ProcessingError.php
  src/main/php/PHPMD/Renderer/BaselineRenderer.php
  src/main/php/PHPMD/Renderer/HTMLRenderer.php
  src/main/php/PHPMD/Report.php
  src/main/php/PHPMD/RuleViolation.php
  src/main/php/PHPMD/TextUI/Command.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/main/php/PHPMD/Utility/ExceptionsList.php
Labels: Refactoring

#1147 Use unpacking inside arrays
  src/main/php/PHPMD/PHPMD.php
  src/main/php/PHPMD/Parser.php
  src/main/php/PHPMD/Renderer/SARIFRenderer.php
  src/main/php/PHPMD/Report.php
  src/main/php/PHPMD/Rule/Design/CountInLoopExpression.php
  src/main/php/PHPMD/RuleSetFactory.php
  src/test/php/PHPMD/Rule/Design/TooManyPublicMethodsTest.php
  src/test/php/PHPMD/TextUI/CommandLineOptionsTest.php
  src/test/php/PHPMD/TextUI/CommandTest.php
Labels: Refactoring

#1157 [3.x] Remove Suhosin workaround
  src/bin/phpmd
Labels: Compatibility, php7.x, Refactoring, php8.x

#1161 Convert PHPCS result to native GitHub format and make it none failing
  .github/workflows/codestyle.yml
Labels: Code Style

#1162 Enable Scrutinizer Analysis (2.x)
  .scrutinizer.yml
Labels: Build scripts

#1163 Enable Scrutinizer Analysis (3.x)
  .scrutinizer.yml
Labels: Build scripts

#1168 Update to latest PDepend 3.x
  composer.json
  src/main/php/PHPMD/Parser.php
Labels: PDepend

#1166 [2.x] Ruleset XML Schema Definition #546
  README.rst
  src/main/resources/rulesets/cleancode.xml
  src/main/resources/rulesets/codesize.xml
  src/main/resources/rulesets/controversial.xml
  src/main/resources/rulesets/design.xml
  src/main/resources/rulesets/naming.xml
  src/main/resources/rulesets/unusedcode.xml
  src/site/resources/web/xml/ruleset_xml_schema_1.0.0.xsd
  src/site/rst/documentation/creating-a-ruleset.rst
  src/site/rst/documentation/writing-a-phpmd-rule.rst
  src/test/resources/files/rulesets/alternative-property-value-syntax.xml
  src/test/resources/files/rulesets/exclude-pattern.xml
  src/test/resources/files/rulesets/pmd-refset1.xml
  src/test/resources/files/rulesets/refset-exclude-all.xml
  src/test/resources/files/rulesets/refset-exclude-one.xml
  src/test/resources/files/rulesets/refset1.xml
  src/test/resources/files/rulesets/refset2.xml
  src/test/resources/files/rulesets/refset3.xml
  src/test/resources/files/rulesets/refset4.xml
  src/test/resources/files/rulesets/ruleset-refs.xml
  src/test/resources/files/rulesets/set-class-file-not-found.xml
  src/test/resources/files/rulesets/set-class-not-found.xml
  src/test/resources/files/rulesets/set1.xml
  src/test/resources/files/rulesets/set2.xml
Labels: Documentation, Website, Configuration

#1169 Handle some null values
  src/main/php/PHPMD/AbstractNode.php
  src/main/php/PHPMD/AbstractRule.php
  src/main/php/PHPMD/Cache/Model/ResultCacheState.php
  src/main/php/PHPMD/Cache/ResultCacheFileFilter.php
  src/main/php/PHPMD/Cache/ResultCacheUpdater.php
  src/main/php/PHPMD/Rule.php
  src/main/php/PHPMD/Rule/Naming/ShortMethodName.php
  src/main/php/PHPMD/Rule/UnusedPrivateMethod.php
  src/main/php/PHPMD/RuleSet.php
  src/main/php/PHPMD/RuleSetFactory.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
  src/main/php/PHPMD/Writer/StreamWriter.php
Labels: PHPStan

#1171 Handle null cases
  phpstan.neon
  src/main/php/PHPMD/Baseline/BaselineValidator.php
  src/main/php/PHPMD/Cache/ResultCacheUpdater.php
  src/main/php/PHPMD/Node/ASTNode.php
  src/main/php/PHPMD/Node/AbstractTypeNode.php
  src/main/php/PHPMD/Node/FunctionNode.php
  src/main/php/PHPMD/Node/MethodNode.php
  src/main/php/PHPMD/PHPMD.php
  src/main/php/PHPMD/Parser.php
  src/main/php/PHPMD/Renderer/AnsiRenderer.php
  src/main/php/PHPMD/Renderer/BaselineRenderer.php
  src/main/php/PHPMD/Renderer/CheckStyleRenderer.php
  src/main/php/PHPMD/Renderer/GitHubRenderer.php
  src/main/php/PHPMD/Renderer/HTMLRenderer.php
  src/main/php/PHPMD/Renderer/SARIFRenderer.php
  src/main/php/PHPMD/Renderer/XMLRenderer.php
  src/main/php/PHPMD/Rule/AbstractLocalVariable.php
  src/main/php/PHPMD/Rule/CleanCode/BooleanArgumentFlag.php
  src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php
  src/main/php/PHPMD/Rule/Controversial/CamelCaseNamespace.php
  src/main/php/PHPMD/Rule/Controversial/CamelCaseVariableName.php
  src/main/php/PHPMD/Rule/Design/CountInLoopExpression.php
  src/main/php/PHPMD/Rule/Design/EmptyCatchBlock.php
  src/main/php/PHPMD/Rule/Naming/ConstructorWithNameAsEnclosingClass.php
  src/main/php/PHPMD/Rule/UnusedFormalParameter.php
  src/main/php/PHPMD/Rule/UnusedLocalVariable.php
  src/main/php/PHPMD/Rule/UnusedPrivateField.php
  src/main/php/PHPMD/RuleSetFactory.php
  src/main/php/PHPMD/TextUI/Command.php
  src/main/php/PHPMD/TextUI/CommandLineOptions.php
Labels: PHPStan
